theia@theiadocker-serendipity2:/home/project$ pip3 install pandas dash
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-1.1.5-cp36-cp36m-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 4.9 MB/s            
Collecting dash
  Downloading dash-2.4.1-py3-none-any.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 71.0 MB/s            
Collecting numpy>=1.15.4
  Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
     |████████████████████████████████| 14.8 MB 45.9 MB/s            
Requirement already satisfied: python-dateutil>=2.7.3 in /home/theia/.local/lib/python3.6/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /home/theia/.local/lib/python3.6/site-packages (from pandas) (2021.3)
Collecting dash-core-components==2.0.0
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Collecting dash-html-components==2.0.0
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting importlib-metadata==4.8.3
  Using cached importlib_metadata-4.8.3-py3-none-any.whl (17 kB)
Collecting dash-table==5.0.0
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Collecting plotly>=5.0.0
  Downloading plotly-5.8.0-py2.py3-none-any.whl (15.2 MB)
     |████████████████████████████████| 15.2 MB 71.0 MB/s            
Requirement already satisfied: Flask>=1.0.4 in /home/theia/.local/lib/python3.6/site-packages (from dash) (1.1.4)
Collecting flask-compress
  Downloading Flask_Compress-1.12-py3-none-any.whl (7.9 kB)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/theia/.local/lib/python3.6/site-packages (from importlib-metadata==4.8.3->dash) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in /home/theia/.local/lib/python3.6/site-packages (from importlib-metadata==4.8.3->dash) (3.6.0)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /home/theia/.local/lib/python3.6/site-packages (from Flask>=1.0.4->dash) (2.11.3)
Requirement already satisfied: click<8.0,>=5.1 in /home/theia/.local/lib/python3.6/site-packages (from Flask>=1.0.4->dash) (7.1.2)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /home/theia/.local/lib/python3.6/site-packages (from Flask>=1.0.4->dash) (1.0.1)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /home/theia/.local/lib/python3.6/site-packages (from Flask>=1.0.4->dash) (1.1.0)
Requirement already satisfied: tenacity>=6.2.0 in /home/theia/.local/lib/python3.6/site-packages (from plotly>=5.0.0->dash) (8.0.1)
Requirement already satisfied: six>=1.5 in /home/theia/.local/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Collecting brotli
  Downloading Brotli-1.0.9-cp36-cp36m-manylinux1_x86_64.whl (357 kB)
     |████████████████████████████████| 357 kB 52.4 MB/s            
Requirement already satisfied: MarkupSafe>=0.23 in /home/theia/.local/lib/python3.6/site-packages (from Jinja2<3.0,>=2.10.1->Flask>=1.0.4->dash) (1.1.1)
Installing collected packages: brotli, plotly, numpy, importlib-metadata, flask-compress, dash-table, dash-html-components, dash-core-components, pandas, dash
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.2.0
    Uninstalling importlib-metadata-4.2.0:
      Successfully uninstalled importlib-metadata-4.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasette 0.59.1 requires httpx>=0.20, but you have httpx 0.19.0 which is incompatible.
flake8 4.0.1 requires importlib-metadata<4.3; python_version < "3.8", but you have importlib-metadata 4.8.3 which is incompatible.
Successfully installed brotli-1.0.9 dash-2.4.1 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 flask-compress-1.12 importlib-metadata-4.8.3 numpy-1.19.5 pandas-1.1.5 plotly-5.8.0
theia@theiadocker-serendipity2:/home/project$ pip install h5py
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Collecting h5py
  Downloading h5py-3.1.0-cp36-cp36m-manylinux1_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 19.4 MB/s            
Requirement already satisfied: cached-property in /home/theia/.local/lib/python3.6/site-packages (from h5py) (1.5.2)
Requirement already satisfied: numpy>=1.12 in /home/theia/.local/lib/python3.6/site-packages (from h5py) (1.19.5)
Installing collected packages: h5py
Successfully installed h5py-3.1.0
theia@theiadocker-serendipity2:/home/project$ pip install typing-extensions
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: typing-extensions in /home/theia/.local/lib/python3.6/site-packages (3.10.0.2)
theia@theiadocker-serendipity2:/home/project$ pip install wheel
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.30.0)
theia@theiadocker-serendipity2:/home/project$ wget "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_dash.csv"
--2022-05-13 17:43:16--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_dash.csv
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2476 (2.4K) [text/csv]
Saving to: ‘spacex_launch_dash.csv’

spacex_launch_dash.csv                100%[=======================================================================>]   2.42K  --.-KB/s    in 0s      

2022-05-13 17:43:16 (200 MB/s) - ‘spacex_launch_dash.csv’ saved [2476/2476]

theia@theiadocker-serendipity2:/home/project$ wget "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/spacex_dash_app.py"
--2022-05-13 18:01:13--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/spacex_dash_app.py
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2110 (2.1K) [text/x-python]
Saving to: ‘spacex_dash_app.py’

spacex_dash_app.py                    100%[=======================================================================>]   2.06K  --.-KB/s    in 0s      

2022-05-13 18:01:13 (72.6 MB/s) - ‘spacex_dash_app.py’ saved [2110/2110]

theia@theiadocker-serendipity2:/home/project$ 

cd '/home/project' && env '/usr/bin/python3' '/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/launcher' '43551' '--' '/home/project/.theia/launch.json'
theia@theiadocker-serendipity2:/home/project$ cd '/home/project' && env '/usr/bin/python3' '/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/launcher' '43551' '--' '/home/project/.theia/launch.json'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.6/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/lib/python3.6/runpy.py", line 236, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "/home/project/.theia/launch.json", line 2
    // Use IntelliSense to learn about possible attributes.
     ^
SyntaxError: invalid syntax
theia@theiadocker-serendipity2:/home/project$ cd '/home/project' && env '/usr/bin/python3' '/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/launcher' '46509' '--' '${spacex_dash_app.py}'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.6/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/lib/python3.6/runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '${spacex_dash_app.py}'
theia@theiadocker-serendipity2:/home/project$ cd '/home/project' && env '/usr/bin/python3' '/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/launcher' '34901' '--' '/home/project/.theia/launch.json'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.6/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/lib/python3.6/runpy.py", line 236, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "/home/project/.theia/launch.json", line 2
    // Use IntelliSense to learn about possible attributes.
     ^
SyntaxError: invalid syntax
theia@theiadocker-serendipity2:/home/project$ cd '/home/project' && env '/usr/bin/python3' '/home/theia/plugins/vscode-python/extension/pythonFiles/lib/python/debugpy/launcher' '46471' '--' '/home/project/spacex_dash_app.py'
/home/project/spacex_dash_app.py:4: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
/home/project/spacex_dash_app.py:5: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "spacex_dash_app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
